### ISSUE TITLE
Colour filter not working

### ISSUE THREAD

**Issue by narayanaraoR** [AlbertGrobas/PolygonImageView#3]
I am trying apply colour filters to the PolygonImageViews but they are not working. 
My code:

```
   ColorMatrix cm = new ColorMatrix();
    cm.setSaturation(0);
    ColorMatrixColorFilter filter = new ColorMatrixColorFilter(cm);
    view.setColorFilter(filter);
```

Any help would be appreciated.

**Comment by AlbertGrobas** [comment]
Ok, it needs override `setColorFilter` like this:

``` java
    @Override
    public void setColorFilter(ColorFilter cf) {
        mPaint.setColorFilter(cf);
        invalidate();
    }
```

I'll do some tests before commit it.

Thanks!

**Comment by narayanaraoR** [comment]
This works perfectly. Thanks Albert. You are awesome.
